version: "3.6"

services:
  shop:
    container_name: "shop"
    build:
      context: ./shop
      dockerfile: Dockerfile
    environment:
      - DB_NAME=shop
      - DB_USER=user
      - DB_PASS=123123
      - DB_URI=db:3306
    depends_on:
      - static
      - db
    ports:
      - "8189:8080"
    volumes:
      - type: bind
        source: ./static/img
        target: /usr/local/tomcat/webapps/images

  db:
    container_name: "db"
    build:
      context: ./db
      dockerfile: Dockerfile
    command: --innodb_use_native_aio=0
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d

  glasscase:
    container_name: "glasscase"
    build:
      context: ./glasscase
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console
      - "61616:61616" # mq

  email:
    container_name: "email"
    build:
      context: ./emailservice
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  static:
    container_name: "static"
    build:
      context: ./static
      dockerfile: Dockerfile
    ports:
      - "8190:8080"
    volumes:
      - type: bind
        source: ./static/img
        target: /home/node/app/img

  orderservice:
    container_name: "order-service"
    build:
      context: ./orderservice
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
